# name: github pages

# on:
#   push:
#     branches:
#       - master
#     tags-ignore:
#       - '*.*'
#     paths-ignore:
#       - .\docs

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out master
#         uses: actions/checkout@master
#         with:
#           submodules: true
#           fetch-depth: 0  
#       - name: Deploy site
#         uses: plopcas/hugo-s3-action@v1.3.0
#         env:
#           AWS_REGION: 'us-east-1'
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           MINIFY: 'true'

# jobs:
#   deploy:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           submodules: true
#           fetch-depth: 0

#       - name: Setup Hugo
#         uses: peaceiris/actions-hugo@v2
#         with:
#           hugo-version: '0.76.4'
#           extended: true

#       - name: Build
#         run: |
#               cd Settings
#               hugo -D
